version: '3.8'

services:
  govchaind:
    build: .
    container_name: govchaind-node
    volumes:
      - govchaind-data:/home/nonroot/.govchain
      - tailscale-ip-share:/var/run/tailscale-ip
    environment:
      - MONIKER=my-node
      # Optional: Manually set the external IP address for the node.
      # If not set, the entrypoint script will try to get it from Tailscale,
      # or discover the public IP (e.g., for VPS deployments).
      # - EXTERNAL_IP=YOUR_PUBLIC_IP_OR_DOMAIN
    ports:
      - "26656:26656"
      - "26657:26657"
    networks:
      - govchain_network
    depends_on:
      - tailscale

  tailscale:
    image: tailscale/tailscale
    container_name: tailscale-sidecar
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - tailscale-state:/var/lib/tailscale
      - tailscale-ip-share:/var/run/tailscale-ip
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=my-node-ts
    networks:
      - govchain_network
    command: sh -c "tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock & tailscale up --authkey=$TS_AUTHKEY --hostname=$TS_HOSTNAME --accept-routes && tailscale ip -4 > /var/run/tailscale-ip/ts_ip && sleep infinity"

networks:
  govchain_network:
    driver: bridge

volumes:
  govchaind-data:
  tailscale-state:
  tailscale-ip-share:
